version: '3.8'
services:
  angular:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '4200:4200'
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    networks:
      - app-network

  nestjs:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./server:/usr/src/app/nestjs
      - /usr/src/app/nestjs/node_modules
    restart: always
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: movie
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: movie
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
    networks:
      - app-network
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

networks:
  app-network: